# PROGRAM 1
## PENEMUAN PENILAIAN
### Hasil Penilaian Maklumbalas Program

**1.1 Profil Peserta**

<a id=tab:1.1></a> 

[Jadual 1.1]: \#tab:1.1

**Jadual 1.1. Profil Peserta**

$$
% Table generated by Excel2LaTeX from sheet 'Program 1'
\begin{table}[htbp]
  \centering
  \caption{Add caption}
    \begin{tabular}{|lrr|}
    \toprule
          & \multicolumn{1}{l}{\textbf{Bilangan}} & \multicolumn{1}{l|}{\textbf{Peratus}} \\
    Jumlah & 47    & 45.2 \\
    \textbf{Jantina} &       &  \\
    Lelaki & 3     & 6.4 \\
    Perempuan & 44    & 93.6 \\
    \textbf{Status Perkahwinan} &       &  \\
    Berkahwin & 25    & 53.2 \\
    Bercerai / Berpisah & 24    & 51.1 \\
    Balu / Duda & 6     & 12.8 \\
    \textbf{Skim Bantuan} &       &  \\
    Bantuan am & 11    & 23.4 \\
    Bantuan kanak-kanak & 37    & 78.7 \\
    Elaun orang kurang upaya & 0     & 0.0 \\
    \bottomrule
    \end{tabular}%
  \label{tab:addlabel}%
\end{table}%

$$

**1.2 Reaksi Peserta Terhadap Pengendalian Program**


*Kepuasan Program*

Tahap persetujuan kepuasan peserta terhadap pengendalian program di ukur berdasarkan perkara seperti di Jadual 1.2.

<a id=tab:1.2></a> 

[Jadual 1.2]: \#tab:1.2

**Jadual 1.2. Taburan skor kepuasan program**

$$
% Table generated by Excel2LaTeX from sheet 'Program 1'
\begin{table}[htbp]
  \centering
  \caption{Add caption}
    \begin{tabular}{lrrrrrrrrr}
    \toprule
    \multicolumn{1}{|c}{\multirow{2}[1]{*}{}} & \multicolumn{1}{c}{\multirow{2}[1]{*}{\textbf{Purata skor}}} & \multicolumn{4}{c}{\textbf{Bilangan }} & \multicolumn{4}{c|}{\textbf{Peratus}} \\
    \multicolumn{1}{|c}{} &       & \multicolumn{1}{c}{\textbf{1}} & \multicolumn{1}{c}{\textbf{2}} & \multicolumn{1}{c}{\textbf{3}} & \multicolumn{1}{c}{\textbf{4}} & \multicolumn{1}{c}{\textbf{1}} & \multicolumn{1}{c}{\textbf{2}} & \multicolumn{1}{c}{\textbf{3}} & \multicolumn{1}{c|}{\textbf{4}} \\
    \multicolumn{1}{|l}{Perhatian} & 3.62  & 1     & 0     & 15    & 31    & 2.1   & 0.0   & 31.9  & \multicolumn{1}{r|}{66.0} \\
    \multicolumn{1}{|l}{Tempat} & 3.64  & 1     & 0     & 14    & 32    & 2.1   & 0.0   & 29.8  & \multicolumn{1}{r|}{68.1} \\
    \multicolumn{1}{|l}{Cadang} & 3.64  & 0     & 0     & 17    & 30    & 0.0   & 0.0   & 36.2  & \multicolumn{1}{r|}{63.8} \\
    \midrule
    \textit{Nota:} &       &       &       &       &       &       &       &       &  \\
    \textit{Perhatian = Saya memberikan perhatian yang sepenuhnya sepanjang program ini.} &       &       &       &       &       &       &       &       &  \\
    \textit{Tempat = Tempat penganjuran program ini memberikan keselesaan kepada proses pembelajaran saya.} &       &       &       &       &       &       &       &       &  \\
    \textit{Cadang = Saya akan mencadangkan program ini kepada orang lain.} &       &       &       &       &       &       &       &       &  \\
    \end{tabular}%
  \label{tab:addlabel}%
\end{table}%
$$

Ulasan:
Secara keseluruhannya, reaksi peserta program  mengikut pengisian program adalah memuaskan dan agak positif bagi pengendalian program. Pihak pengendali boleh menambahbaik program pada masa akan datang dengan mensasarkan skor tertinggi (4) bagi kesemua aspek dalam kalangan kesemua peserta (100%). 


*Kepuasan Program Mengikut Pengisian*
Tahap persetujuan kepuasan peserta mengikut pengisian program di ukur berdasarkan  perkara-perkara seperti di Jadual 3. 

<a id=tab:1.3></a> 

[Jadual 1.3]: \#tab:1.3

**Jadual 1.3. Taburan skor Kepuasan Peserta Mengikut Pengisian Program**

$$
% Table generated by Excel2LaTeX from sheet 'Program 1'
\begin{table}[htbp]
  \centering
  \caption{Add caption}
    \begin{tabular}{|lrrrrrrrrr|}
    \toprule
    \multirow{2}[1]{*}{} & \multicolumn{1}{c}{\multirow{2}[1]{*}{\textbf{Purata skor}}} & \multicolumn{4}{c}{\textbf{Bilangan }} & \multicolumn{4}{c|}{\textbf{Peratus}} \\
          &       & \multicolumn{1}{c}{\textbf{1}} & \multicolumn{1}{c}{\textbf{2}} & \multicolumn{1}{c}{\textbf{3}} & \multicolumn{1}{c}{\textbf{4}} & \multicolumn{1}{c}{\textbf{1}} & \multicolumn{1}{c}{\textbf{2}} & \multicolumn{1}{c}{\textbf{3}} & \multicolumn{1}{c|}{\textbf{4}} \\
    \textbf{Tajuk 1: Trans minda @ Potensi} &       &       &       &       &       &       &       &       &  \\
    Penceramah & 3.64  & 1     & 0     & 14    & 32    & 2.1   & 0.0   & 29.8  & 68.1 \\
    Aktiviti & 3.68  & 0     & 0     & 15    & 32    & 0.0   & 0.0   & 31.9  & 68.1 \\
    Manfaat & 3.66  & 0     & 0     & 16    & 31    & 0.0   & 0.0   & 34.0  & 66.0 \\
    \textbf{Tajuk 2: Trans minda @ Keibubapaan Positif} &       &       &       &       &       &       &       &       &  \\
    Penceramah & 3.60  & 1     & 0     & 16    & 30    & 2.1   & 0.0   & 34.0  & 63.8 \\
    Aktiviti & 3.62  & 0     & 0     & 18    & 29    & 0.0   & 0.0   & 38.3  & 61.7 \\
    Manfaat & 3.62  & 0     & 0     & 18    & 29    & 0.0   & 0.0   & 38.3  & 61.7 \\
    \textbf{Tajuk 3: Trans minda @ Pengurusan Kewangan} &       &       &       &       &       &       &       &       &  \\
    Penceramah & 3.64  & 0     & 0     & 17    & 30    & 0.0   & 0.0   & 36.2  & 63.8 \\
    Aktiviti & 3.60  & 0     & 0     & 19    & 28    & 0.0   & 0.0   & 40.4  & 59.6 \\
    Manfaat & 3.70  & 0     & 0     & 14    & 33    & 0.0   & 0.0   & 29.8  & 70.2 \\
    \bottomrule
    \end{tabular}%
  \label{tab:addlabel}%
\end{table}%
$$


Ulasan:
Secara keseluruhannya, reaksi peserta program  mengikut pengisian program adalah memuaskan dan agak positif bagi ketiga-tiga sesi ceramah. Pihak pengendali boleh menambahbaik program pada masa akan datang dengan mensasarkan skor tertinggi (4) bagi kesemua aspek dalam kalangan kesemua peserta (100%). 

*Tahap pembelajaran*

Skor pembelajaran peserta program diukur dengan menggunakan 5-skala Likert di mana skala 1 bermaksud Sangat Lemah atau Sangat Rendah dan skala 5 bermaksud Sangat Baik atau Sangat Tinggi. Setiap peserta dikehendaki untuk memberikan penilaian mereka pada sebelum dan selepas menghadiri program tersebut.

<a id=tab:1.4></a> 

[Jadual 1.4]: \#tab:1.4

**Jadual 1.4. Taburan Skor Pembelajaran Sebelum dan Selepas Menghadiri Program**

$$
% Table generated by Excel2LaTeX from sheet 'Program 1'
\begin{table}[htbp]
  \centering
  \caption{Add caption}
    \begin{tabular}{|lrr|}
    \toprule
    \multirow{2}[1]{*}{} & \multicolumn{2}{c|}{\textbf{Purata skor}} \\
          & \multicolumn{1}{l}{\textbf{Sebelum}} & \multicolumn{1}{l|}{\textbf{Selepas}} \\
    Tahap Motivasi & 3.42  & 4.67 \\
    Tahap Pengetahuan  &       &  \\
    Kemahiran Keibubapaan Positif & 3.72  & 4.79 \\
    Ilmu pengurusan kewangan keluarga & 3.89  & 4.81 \\
    Tahap Keyakinan & 3.81  & 4.83 \\
    Tahap Komitmen & 3.81  & 4.79 \\
    \bottomrule
    \end{tabular}%
  \label{tab:addlabel}%
\end{table}%
$$

Ulasan:
Secara keseluruhannya, peningkatan terhadap tahap motivasi (sebelum: 3.4; selepas: 4.7), pengetahuan kemahiran keibubapaan positif (sebelum: 3.7; selepas: 4.8), pengetahuan ilmu pengurusan kewangan keluarga (sebelum: 3.9; selepas: 4.8), keyakinan (sebelum: 3.8; selepas: 4.8) dan komitmen (sebelum: 3.8; selepas: 4.8) peserta program adalah ketara lebih baik selepas mereka selesai hadiri program ini. Secara keseluruhannya, program ini berjaya meningkatkan tahap pembelajaran peserta. 

### Hasil Penilaian Keberkesanan Program

Data akan mula dikutip selepas 2 bulan dari tarikh program. Hasil penilaian akan dilaporkan kemudian. 
